### ISSUE TITLE
Register mail delivery on localhost

### ISSUE THREAD

**Issue by jirevwe** [Helpmonks/haraka-plugin-mongodb#1]
Hi... I like your plugin, was thinking of writing one myself.

I'm trying to send mails with my own localhost domain to test the mail delivery, because inbound messages are not being saved to mongodb (I actually dunno if it'll work) eg ray@test.com to david@test.com

The delivery and queue params are already enabled. Outbound mails get stored.
```
[enable]
queue=yes
delivery=yes
```
Is it meant to work like this or do I need to set it up on a live server?

**Comment by thenitai** [comment]
Not exactly sure what you mean. Do you want to store the result of outgoing emails?

If so, just set delivery=yes and given that you have a MongoDB connection (there is output in the log) you should be fine.

Did you add the plugin to the config/plugin file also? 

What does the log output tell you when you start Haraka?

**Comment by jirevwe** [comment]
> Not exactly sure what you mean. Do you want to store the result of outgoing emails?

Yes... I actually don't know how to send outbound mails using only localhost, I've only been able to intercept an inbound mail.

> Did you add the plugin to the config/plugin file also?

Yes I did...

> What does the log output tell you when you start Haraka?
