### ISSUE TITLE
TypeError: body_text_encoded.replace is not a function

### ISSUE THREAD

**Issue by tiltroom** [Helpmonks/haraka-plugin-mongodb#16]
Hi everyone,
I'm experiencing an issue with this module when "queue=yes" on last release (didn't try older versions yet)

NOTICE] [61F2A81E-8D12-4ADE-ACCF-E31E176D1556.1] [core] message mid="<cYz4-pUBLXlz_n6NyySgRPlo4R-cqCPCr7Zs21AWAPoOfeCq1ZDY1EtnzT1z0AL0JwW89qvD5J6-Ru829Y8QeKqnJfu7jaXn_PWh1wXUSxk=@protonmail.com>" size=2559 rcpts=1/0/0 delay=0.009 code=CONT msg=""
[INFO] [-] [mongodb] finished uploading all 0 attachments
[CRIT] [-] [core] TypeError: body_text_encoded.replace is not a function
[CRIT] [-] [core]     at _formatQuotedPrintableBody (/root/Haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:520:58)
[CRIT] [-] [core]     at getBodyOfTypeFromChildren (/root/Haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:317:36)
[CRIT] [-] [core]     at getBodyOfTypeFromChildren (/root/Haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:402:24)
[CRIT] [-] [core]     at getBodyByField (/root/Haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:268:13)
[CRIT] [-] [core]     at _extractBody (/root/Haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:216:17)
[CRIT] [-] [core]     at /root/Haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:66:52
[CRIT] [-] [core]     at nextTask (/root/Haraka/node_modules/async/dist/async.js:4576:27)
[CRIT] [-] [core]     at Object.waterfall (/root/Haraka/node_modules/async/dist/async.js:4587:9)
[CRIT] [-] [core]     at Object.awaitable [as waterfall] (/root/Haraka/node_modules/async/dist/async.js:208:32)
[CRIT] [-] [core]     at Object.getHtmlAndTextBody (/root/Haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:50:9)
[NOTICE] [-] [core] Shutting down
[NOTICE] [-] [core] worker 1 exited with error code: 1
[NOTICE] [-] [core] worker started worker=2 pid=3769

And from this point on it just keep crash looping.

**Comment by oronoa** [comment]
You are probably using node 15, try to convert body_text_encoded from Buffer to string like so 

```
var new_var= body_text_encoded.toString('utf-8')
var fixed_body = new_ver ? new_var.replace(/=\n/gm, '') : '';
```

**Comment by mikej165** [comment]
I'm seeing this problem as well, even after downgrading to Node 12.

**Comment by thenitai** [comment]
Upgrade to the latest. Has nothing to do with node version.

**Comment by mikej165** [comment]
According to Changes.md, I'm running the latest version.

For what it's worth, the prior suggestion by @oronoa work fine but there is a typo in the 2nd line. Replace 'new_ver' with 'new_var'

**Comment by thenitai** [comment]
We cannot replicate the issue. However, we will run the updated code for a while here and then will release it, if it helps.

**Comment by mikej165** [comment]
I agree this is strange. I'm running the latest versions of both Haraka and the mongo plugin, both installed via npm. They're running off the official node 12 Docker image (node:12.21.0-buster), though I've tried all the way up to version 15. No other modules or plugins are installed.

Happy to provide additional info on my environement if it helps. 

The patch detailed above does do the trick here.

**Comment by thenitai** [comment]
Ok, we've done all our testing and it seems to work without any issues. I've made a 1.8.1 release. Going to close this now. Thank you.

**Comment by mikej165** [comment]
I regenerated my container with the new version and everything is working perfectly. Thanks for deploying this so quickly.
