### ISSUE TITLE
Support for useUnifiedTopology

### ISSUE THREAD

**Issue by dylan-hart** [Helpmonks/haraka-plugin-mongodb#17]
Is there planned support for useUnifiedTopology in the MongoClientOptions object?

(https://github.com/Helpmonks/haraka-plugin-mongodb/blob/develop/index.js#L98)

Due to my configuration, omitting useUnifiedTopology causes the plugin to throw:
```consoel
MongoNetworkError: failed to connect to server [...] on first connect [Error: connect ECONNREFUSED ... ]
```

I could make a pr - would exposing all MongoClientOptions options via the mongodb.ini make sense, or just this one?

**Comment by thenitai** [comment]
That's just an option that has no effect if enabled or not, correct? I know we have it set to true in our app ( https://helpmonks.com ).

If so, I can just add it to the client options.

**Comment by dylan-hart** [comment]
Just to check, I wrote a separate, simple node.js application to connect to the same mongo instance. It connects when it's set to true, and throws the error from above when it's not set to true.

I'm not sure why this is - I don't know much about mongo's topology features. If I figure it out, I'll update. In the meantime I'd be grateful to have the option. I've had success with overwriting ../node_modules/haraka-plugin-mongodb/index.js with a version that sets the setting to true, and that's acceptable enough to me for now.
