### ISSUE TITLE
Notify when email is arrived

### ISSUE THREAD

**Issue by scofield-ua** [Helpmonks/haraka-plugin-mongodb#19]
Hello. Is there a built-in way to notify other application every time email is received? Maybe through some webhook or something.

Currently, I'm thinking of using the watch functionality of mongdb - https://docs.mongodb.com/drivers/node/current/usage-examples/changeStream/ and just watch collection with emails.

But maybe there is a more preferable way? Thanks.

**Comment by thenitai** [comment]
That's not really related to this plugin. That said, you could either hook into the delivery function in this plugin's code and execute an external function to notify your service or you can run a script that checks the database collection for new emails and notifies the services (recommended).
