### ISSUE TITLE
Can we store attachments files in mongodb files ?

### ISSUE THREAD

**Issue by guillaumebadin** [Helpmonks/haraka-plugin-mongodb#2]

**Comment by thenitai** [comment]
You mean in the MonogDB file system? If so, no. It stores attachments on the file system.

I'm ging to close this, but feel free to comment or re-open.

**Comment by guillaumebadin** [comment]
Yes I Mean in the MongoDB File system.

**Comment by thenitai** [comment]
Honestly, I don't have much experience with the MongoDB filesystem. If there is a path that is exposed on the OS filesystem it might work.

**Comment by gnoireaux** [comment]
What about storing attachments as documents in a collection?

**Comment by thenitai** [comment]
> What about storing attachments as documents in a collection?

The attachment object is stored along the rest of the email as a document. Just the file itself is stored on disk.

**Comment by gnoireaux** [comment]
Thanks a lot for your answer @thenitai !

I tried sending through the plugin an email with an 7 745 bytes attachment. The json I read through Robo3T had 10327 varying chars followed by 77055 times the letter "A".
Did I misconfigure something?

The test email has a subject line, three words in the body and its 8kB attachment. I've got a bunch of them in a collection, no other kind of object. The `avgObjSize` from `db.getCollection('email_incoming_haraka').stats()` is 222047. Is it 222 thousand bytes? Is it normal? I feel there is something I do not understand.
Thank you  for your time!

**Comment by thenitai** [comment]
You did not state what version of the plugin you use. 

Also, the plugin simply parses the email and stores all its headers in a document. The file itself is stored on disk.

There are some settings on the mongodb.ini file for attachments. Make sure those are correct as well.
