### ISSUE TITLE
Add support for smtp_forward plugin

### ISSUE THREAD

**Issue by kayrus** [Helpmonks/haraka-plugin-mongodb#20]
https://haraka.github.io/plugins/queue/smtp_forward/ config allows to specify an SMTP server with credentials to forward emails to.
It can also forward emails to different SMTP servers according to the recipient/sender domains.

In case when the email cannot be delivered right away, the credentials and the backend hostname info must be stored in a queue along with the message body, so the next attempt would use the corresponding `user:pass@host:587` backend server.

**Comment by thenitai** [comment]
Hi,

You wrote a description of what that plugin does. However, I don't get what this has to do with this plugin? Is there a question in there that I've missed?

**Comment by kayrus** [comment]
@thenitai I haven't noticed that it saves SMTP host and credentials for further tries https://github.com/Helpmonks/haraka-plugin-mongodb/blob/master/index.js#L326-L357 :\ did I miss something?

**Comment by kayrus** [comment]
I also didn't find the logic that retries to send an email from mongodb.

**Comment by thenitai** [comment]
You are mistaken about what this plugin does. Please read the description.

**Comment by kayrus** [comment]
I think there is a general confusion about the terms haraka uses. From me a queue is a special storage haraka uses to store emails for further retry. Same as postfix or exim. Currently this behavior corresponds only to the local disk queue (`queue` directory).
 It looks like all queue plugins don't follow this approach and `queuing` means just to **deliver** emails to external storage with no other actions from haraka side.

See similar references I found with this confusion:
* https://github.com/haraka/Haraka/issues/3016
* https://github.com/haraka/Haraka/issues/2923
* https://github.com/haraka/Haraka/issues/2930

@thenitai could you please explain the use case for your config? Why do you store emails in mongo if haraka doesn't process them afterwards? Do you use an separate application to access these emails?
